CREATE TABLE USUARIOS (
	ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR2(70),
	PASSWORD VARCHAR2(70));

CREATE TABLE CATEGORIAS (
	ID_CATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE_CAT VARCHAR2(50));

CREATE TABLE PRODUCTOS (
	ID_PRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,
	NOMBRE_PROD VARCHAR2(50),
	DESCRIPCION VARCHAR2(70),
	ID_CATEGORIA INTEGER,
	PRECIO NUMBER(10,2),
	DESCUENTO NUMBER(5,2),
	ELIMINADO INTEGER DEFAULT 0,
	CONSTRAINT FK_PROD_CAT FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA));
	
	INSERT INTO USUARIOS VALUES (1, 'Admin', 'Admin');
	INSERT INTO USUARIOS VALUES (2, 'Usuario', 'Usuario');
	
	INSERT INTO CATEGORIAS VALUES (1, 'Arroces y pastas');
	INSERT INTO CATEGORIAS VALUES (2, 'Asados');
	INSERT INTO CATEGORIAS VALUES (3, 'Pescados');
	INSERT INTO CATEGORIAS VALUES (4, 'Postres caseros');
	INSERT INTO CATEGORIAS VALUES (5, 'Bebidas');
	
	INSERT INTO PRODUCTOS VALUES (1, 'Coca Cola', 'Bebida para todas las edades', 5, 2.50, 0.00, 0);